### PR TITLE
Update/cosmwasm 1.2 (CodeInfo, Instantiate2)

### PR DESCRIPTION
**Pull request by Kayanski**
This PR aims at introducing cosmwasm_1_2 support for cw_multi_test.

This PR concentrates on 2 new additions : 

The WasmQuery::CodeInfo query.

The WasmMsg::Instantiate2 message.

Those 2 changes were made in order to be able to use the instantiate2 message inside contracts and test against it.

# Implementation Details
## CodeIndo Query
This query aims at provding informaton to the user about uploaded codes. Here is the structure of the [response awaited from that query](https://github.com/CosmWasm/cosmwasm/blob/v1.2.0/packages/std/src/query/wasm.rs#L80) 
```rust
pub struct CodeInfoResponse {
    pub code_id: u64,
    /// The address that initially stored the code
    pub creator: String,
    /// The hash of the Wasm blob
    pub checksum: HexBinary,
}
```
For the creator field, to not overload the cw_multi_test field, we assume that the creator is fixed to a user (CODE_CREATOR)
For the checksum field, as the contracts don't really have the possiblity to compute that esaily from functions, I decided to create a `mock_checksum` function that creates mock checksums, base on the code id of the wasm. 
Because `cw_multi_test` is supposed to be a non-critical testing platform (with very little verification), this is sufficient for now.

## Instantiate2 Message
The instantiate2 message is just the same as the instantiate one, except the address is deterministic. cosmwasm_std provides nice helpers to get the contract address, and we use them in the implementation. This functionality bypasses the `AddressGenerator` structure which MIGHT be a design mistake.
Generating an address using cosmwasm_std::MockApi however, doesn't work, because the canonical address have a fixed length different from the actual on-chain ones that instantiate2 creates.
We propose to replace the [`MockApi`](https://github.com/CosmWasm/cosmwasm/blob/main/packages/std/src/testing/mock.rs#L113) with a simpler [`MockSimpleApi`](https://github.com/CosmWasm/cw-multi-test/pull/56/files#diff-adea2445327e39eb215de697b440dbbc02135357380fb612a10a9e659129a46bR6) to be able to generate addresses using the instantiate2 procedure.

# Remaining Tasks
- [x] Unit Tests
- [ ] Replace the existing api object with a simpler MockApi that allows for custom instantiate2 addresses

# Relations
Solves #39 
Solves #49

### CODE REVIEW

**Comment by DariuszDepta** [comment]
Hi @Kayanski, I guess PR #57 and PR #65 address the ideas reported in this PR. Could you take a look at these and if you have any comments then let us discuss them. If your needs are just fulfilled, then let us close this PR. Just let me know what you think.

**Comment by Kayanski** [comment]
> Hi @Kayanski, I guess PR #57 and PR #65 address the ideas reported in this PR. Could you take a look at these and if you have any comments then let us discuss them. If your needs are just fulfilled, then let us close this PR. Just let me know what you think.

Yes.the former

**Comment by DariuszDepta** [comment]
Hi @Kayanski, we release all functionalities described by this PR in version 0.18.0 of multitest. So I am closing this PR. When new requirements arise, please submit separate PR. Thanks.

**Comment by Kayanski** [comment]
Thank you a lot, everything is working perfectly ! However, this adds complexity because one needs to deal with actual bech32 addresses. I think this complexity is needed so I do like the changes !

**Pull request closed without merging**
