### PR TITLE
Add message SetWithdrawAddress to distribution module

### PR DESCRIPTION
**Pull request by 0xekez**
While working on this I realized that there is no delegation module query type in [cosmwasm-std](https://github.com/CosmWasm/cosmwasm/tree/main/packages/std/src/query). Would be interested in thoughts about adding that and what the proper ordering is.

### CODE REVIEW

**Review by ueco-jb — APPROVED** [review]
LGTM
Personally I'd prefer to have a separate test case for that (in case you need to debug it in the future; it's better to have more specialized tests then couple monolithic ones), but I noticed that those tests weren't small ones to begin with so it's not a big deal.

**Comment by 0xekez** [comment]
@ueco-jb thanks for the review! i added an individual test for this as well.

**Comment by JakeHartnell** [comment]
What are the chances we could see this in a release soon?

**Comment by 0xekez** [comment]
@chipshort rebased! let me know if there are any other changes you'd like to see.

**Pull request merged**
